### ISSUE TITLE
[ONBOARDING]

### ISSUE THREAD

**Issue by KDNeufeld** [bcgov/jag-file-submission#1253]
After this issue has been opened, please provide the following information:

- contact email that admins can reach you at 
  - kevin.neufeld@nttdata.com
- a brief description of what you're looking to accomplish by integrating with the efiling-hub
  - per the [onboarding documentation](https://bcgov.github.io/jag-file-submission/#/onboarding), requesting OpenID connect info.  Using Bob Ross results in an "Authorized users only" error when running the app locally - I think I need other credentials.
- a link to github repository of the application that is requesting access to the efiling-hub
  - https://github.com/bcgov/jag-file-submission/tree/master/src/frontend/efiling-frontend
- a list of the types of documents you're looking to upload to the efiling-hub
  - test documents

**Comment by alexjoybc** [comment]
can we close this @KDNeufeld ?

**Comment by KDNeufeld** [comment]
Yes, this can be closed now.
