### ISSUE TITLE
Code Climate - Issue Tracking for Demo

### ISSUE THREAD

**Issue by akroon3r** [bcgov/jag-file-submission#205]
Shelly from BCDevExchange would like us to track (pros/cons) that we come across during the implementation of Code Climate. 

Feel free to add comments as you see fit.

**Comment by akroon3r** [comment]
WIP - Tracking the CC_TEST_REPORTER_ID Issue

**Comment by akroon3r** [comment]
WIP - Tracking the Java Interface Issue, link specific lack of test case in cc-test-reporter repository

**Comment by akroon3r** [comment]
WIP - Badge vs WebApp reporting %

**Comment by akroon3r** [comment]
WIP - Steps required to combine reports from java API and javascript frontend

**Comment by sdevalapurkar-bcgov** [comment]
potential con: coverage issue where it seems like the coverage is not normalized. If n lines of code are removed, then the test coverage can go down as a result even though this should not be the case.
